[tox]
envlist = {py310}-django{42,52},py{312,313,314}-django{42,52,60}
[testenv]
basepython =
    py310: python3.10
    py312: python3.12
    py313: python3.13
    py314: python3.14
deps =
    django42: django<4.2.99
    django52: django<5.2.99
    django60: django<6.0.99
    coverage
    cryptography>=39
    pem>=21.1.0
    python-dateutil
commands = python manage.py test --settings 'test_settings'
